version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY}
    restart: unless-stopped
    # For development, you can mount the source code to enable hot reloading
    # volumes:
    #  - .:/app
    #  - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
